// **---------------------------------------------------------------------+
// ** 文件
// **---------------------------------------------------------------------+
// ** 版权所有：江西佰商科技有限公司. 官网：https://www.tigshop.com
// **---------------------------------------------------------------------+
// ** 作者：Tigshop团队，yq@tigshop.com
// **---------------------------------------------------------------------+
// ** 提示：Tigshop商城系统为非免费商用系统，未经授权，严禁使用、修改、发布
// **---------------------------------------------------------------------+

package com.tigshop.security.api.config;

/**
 * 白名单配置
 *
 * @author Tigshop团队
 */
public class WhiteListConfig {
    public static final String[] URL_WHITELIST = {
            // 行为验证
            "/api/common/verification/*",
            "/adminapi/common/verification/*",
            "/api/common/csrf/**",
            "/doc.html",
            "/v3/api-docs/**",
            "/swagger-ui.html",
            "/swagger-ui/**",
            "/webjars/**",
            "/static/**",
            "/swagger-resources/**",
            "/favicon.ico",
            "/api/article/article/list",
            "/api/article/article/newsInfo",
            "/api/article/article/issueInfo",
            "/api/article/category/list",
            "/api/article/category/indexBzzxList",
            "/api/common/config/base",
            "/api/common/config/mobileAreaCode",
            "/api/common/config/afterSalesService",
            "/api/common/config/initConfigSettings",
            "/api/common/config/themeSettings",
            "/api/common/config/getLoginProtocol",
            "/api/common/config/getLoginProtocolContent",
            "/api/common/i18n/getLocaleTranslations",
            "/api/common/i18n/getLocales",
            "/api/common/i18n/getDefaultLocale",
            "/api/common/log",
            "/api/common/pc/getHeader",
            "/api/common/pc/getNav",
            "/api/common/pc/getCatFloor",
            "/api/common/util/qrCode",
            "/api/common/util/miniCode",
            "/api/common/recommend/guessLike",
            "/api/common/verification/captcha",
            "/api/common/verification/check",
            "/api/common/verification/verification",
            "/api/common/currency/getCurrency",
            "/api/common/translate/translate",
            "/api/home/home/index",
            "/api/home/home/pcIndex",
            "/api/home/home/getRecommend",
            "/api/home/home/getSeckill",
            "/api/home/home/getCoupon",
            "/api/home/home/mobileCatNav",
            "/api/home/home/mobileNav",
            "/api/home/home/memberDecorate",
            "/api/home/home/getCustomerServiceConfig",
            "/api/home/home/friendLinks",
            "/api/home/share/import",
            "/api/salesman/product/list",
            "/api/salesman/content/detail",
            "/api/salesman/content/list",
            "/api/salesman/material/detail",
            "/api/salesman/material/list",
            "/api/salesman/material/category",
            "/api/salesman/salesman/userInfo",
            "/api/order/pay/index",
            "/api/order/pay/checkStatus",
            "/api/order/pay/create",
            "/api/order/pay/notify/*",
            "/api/order/pay/refundNotify/*",
            "/api/product/exchange/list",
            "/api/product/exchange/detail",
            "/api/product/product/detail",
            "/api/product/product/getComment",
            "/api/product/product/getCommentList",
            "/api/product/product/getFeedbackList",
            "/api/product/product/getProductAmount",
            "/api/product/product/getProductAvailability",
            "/api/shop/shop/detail",
            "/api/product/product/list",
            "/api/product/product/getCoupon",
            "/api/product/product/promotion",
            "/api/product/product/getRelated",
            "/api/product/product/priceInquiry",
            "/api/shop/shop/decorate",
            "/api/shop/shop/category",
            "/api/shop/shop/parentTree",
            "/api/shop/shop/shopHead",
            "/api/shop/shop/list",
            "/api/shop/shop/import",
            "/api/shop/shop/pickupList",
            "/api/shop/shop/storeList",
            "/api/shop/shop/storeDetail",
            "/api/shop/category/tree",
            "/api/shop/category/parentTree",
            "/api/search/search/getFilter",
            "/api/search/search/getProduct",
            "/api/search/search/getAttributeSuggestions",
            "/api/search/searchGuess/index",
            "/api/sys/region/*",
            "/api/user/login/*",
            "/api/order/pay/*",
            "/api/user/regist/registAct",
            "/api/category/category/**",
            "/api/decorate/discrete/getOpenAdvertising",
            "/ws/**",
            "/api/socket/send",
            "/api/user/oauth/**",
            "/api/product/product/isCollect",
            "/api/appVersion/*",
            "/api/common/recommend/getProductIds",
            "/api/shop/shop/head",
            "/api/map/positioning/*",
            "/api/shop/shop/head",
            "/api/user/login/sendCode"
    };
}