# 新增固定运费
ALTER TABLE `product`
    ADD COLUMN `fixed_shipping_type` tinyint(2) NULL DEFAULT 2 COMMENT '运费类型1固定运费2运费模板',
    ADD COLUMN `fixed_shipping_fee` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '固定运费金额';

# 新增品牌店铺审核
ALTER TABLE brand
    ADD COLUMN `shop_id` int(13) NOT NULL DEFAULT '0' COMMENT '店铺id',
    ADD COLUMN `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '审核状态:0:待审核,1:审核通过,2:已拒绝',
    ADD COLUMN `reject_remark` TEXT COMMENT '拒绝原因';
UPDATE brand SET `status`= 1;

# 新增最后登录时间
ALTER TABLE shop ADD COLUMN last_login_time int(13) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后登录时间';

# 新增等级的最低成长值
ALTER TABLE `user_rank`
    MODIFY COLUMN `min_growth_points` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '该等级的最低成长值（升级条件）';

# 新增默认配送方式
INSERT INTO `config`(`biz_code`, `biz_val`, `create_time`, `create_by_id`, `create_by_name`, `update_time`, `update_by_id`, `update_by_name`, `is_del`) VALUES ('defaultLogisticsName', '普通快递', 1750040834, 1, 'admin', 1750040834, 1, 'admin', 0);

# 新增默认配置 SQL
INSERT INTO `config` ( `biz_code`, `biz_val`, `create_time`, `create_by_id`, `create_by_name`, `update_time`, `update_by_id`, `update_by_name`, `is_del` ) VALUES (  'defaultCopyright', '© 2018 江西佰商科技版权所有', 1744773841, 0, '', 1745829791, 0, '', 0 );
INSERT INTO `config` ( `biz_code`, `biz_val`, `create_time`, `create_by_id`, `create_by_name`, `update_time`, `update_by_id`, `update_by_name`, `is_del` ) VALUES (  'defaultTechSupport', 'static/mini/images/common/default_tech_support.png', 1744773841, 0, '', 1745829791, 0, '', 0 );

# 订单优化 SQL
alter table `order`
    add mark tinyint(2) default 0 null comment '标记 12345';

# 1. 创建备份表（结构与原表相同）
CREATE TABLE IF NOT EXISTS authority_backup LIKE authority;

# 2. 将原表数据插入到备份表中
INSERT INTO authority_backup SELECT * FROM authority;

# 新增的权限菜单
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (21, 'codeFileManage', '代码生成', 20, 50, 0, '[]', 'authority/code_file/index', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (272, 'jgj', 'ghjhg', 270, 50, 0, '[]', 'fggj', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000397, 'baseBasicManage', '基础信息', 39, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveBasicManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000398, 'baseProductManage', '商品设置', 39, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingProductManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000399, 'baseShoppingManage', '交易设置', 39, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingShoppingManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000400, 'baseOrderManage', '订单设置', 39, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingsOrderManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000401, 'baseNoticeManage', '通知设置', 10000405, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingNotifyManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000402, 'baseServiceManage', '客服设置', 39, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingKefuManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000403, 'globalSetting', '全局设置', 38, 50, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingsGlobalManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000405, 'messageSetting', '消息设置', 15, 54, 1, '[]', '', 'iconfont-tig icon-31pinglun', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000406, 'licensedSetting', '授权设置', 15, 55, 1, '[]', '', 'iconfont-tig icon-shouquanshezhi', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000407, 'copyright', '版权设置', 10000406, 50, 0, '[]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000408, 'salesOverview', '销售统计', 1, 50, 1, '[]', '', 'iconfont-tig icon-xiaoshoutongji', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000409, 'userOverview', '用户统计', 1, 50, 1, '[]', '', 'iconfont-tig icon-yonghutongji', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000410, 'commodityManage', '商品管理', 2, 50, 1, '[]', '', 'iconfont-tig icon-shangpinguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000411, 'stockControl', '库存管理', 2, 52, 1, '[]', '', 'iconfont-tig icon-kucunguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000412, 'quotationManage', '询价管理', 2, 53, 1, '[]', '', 'iconfont-tig icon-xunjiaguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000413, 'promotionOverview', '营销管理', 5, 50, 1, '[]', '', 'iconfont-tig icon-yingxiaoguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000414, 'orderManagement', '订单管理', 8, 50, 1, '[]', '', 'iconfont-tig icon-wenzhangguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000415, 'aftersaleManagement', '售后管理', 8, 50, 1, '[]', '', 'iconfont-tig icon-shouhouguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000416, 'shopManagement', '店铺管理', 10000306, 50, 1, '[]', '', 'iconfont-tig icon-dianpuguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000417, 'fundsManagement', '资金管理', 10000306, 50, 1, '[]', '', 'iconfont-tig icon-zijinguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000418, 'distributionSettings', '分销设置', 10000337, 51, 1, '[]', '', 'iconfont-tig icon-fenxiaoshezhi', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000420, 'loginSetting', '登录设置', 38, 51, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveSettingsSaveLoginManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000421, 'articleManagement', '文章管理', 10, 50, 1, '[]', '', 'iconfont-tig icon-dingdanguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000422, 'userManagement', '会员管理', 11, 50, 1, '[]', '', 'iconfont-tig icon-huiyuanguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000423, 'realNameAuthentication', '实名认证', 11, 50, 1, '[]', '', 'iconfont-tig icon-shimingrenzheng', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000424, 'messagegManage', '消息管理', 11, 50, 1, '[]', '', 'iconfont-tig icon-31pinglun', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000428, 'administrator', '管理员', 14, 50, 1, '[]', '', 'iconfont-tig icon-guanliyuan', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000429, 'suppliers', '供应商', 14, 50, 1, '[]', '', 'iconfont-tig icon-gongyingshang', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000430, 'privilege', '系统权限', 14, 50, 1, '[]', '', 'iconfont-tig icon-quanxian1', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000439, 'paymentSetting', '支付设置', 38, 52, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"uploadFileModifyManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000440, 'userfundsManagement', '资金管理', 12, 50, 1, '[]', '', 'iconfont-tig icon-zijinguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000441, 'refundManagement', '退款管理', 12, 52, 1, '[]', '', 'iconfont-tig icon-tuikuanguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000442, 'transactionManagement', '交易管理', 12, 53, 1, '[]', '', 'iconfont-tig icon-jiaoyiguanli', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000443, 'salesOverview', '销售统计', 10001, 5, 1, '[]', '', 'iconfont-tig icon-xiaoshoutongji', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000444, 'orderManagement', '订单管理', 10001, 2, 1, '[]', '', 'iconfont-tig icon-dingdanguanli', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000445, 'aftersaleManagement', '售后管理', 10001, 3, 1, '[]', '', 'iconfont-tig icon-shouhouguanli', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000450, 'commodityManage', '商品管理', 10001, 4, 1, '[]', '', 'iconfont-tig icon-shangpinguanli', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000451, 'brandManage', '品牌管理', 10000450, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000452, 'commentManage', '评价管理', 10000450, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000453, 'productAttributesTplManage', '属性模板', 10000450, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000454, 'stockControl', '库存管理', 10001, 6, 1, '[]', '', 'iconfont-tig icon-kucunguanli', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000455, 'productInventoryLogManage', '库存日志', 10000454, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000456, 'promotionManage', '营销概览', 10005, 50, 1, '[]', '', 'iconfont-tig icon-yingxiaogailan', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000457, 'promotionOverview', '营销管理', 10005, 50, 1, '[]', '', 'iconfont-tig icon-yingxiaoguanli', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000458, 'accountManagement', '账号管理', 10000463, 3, 1, '[]', '', 'iconfont-tig icon-guanlizhanghao', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000459, 'accountEditingManage', '账号设置', 10000458, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000460, 'userAuthenticationManage', '认证设置', 10000423, 1, 1, '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"saveAuthSettingsManage"}]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000461, 'financialLogManage', '资金明细', 10000291, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000462, 'deliverManage', '发货管理', 10000414, 51, 1, '[]', '', '', 0, 'admin');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000463, 'setting', '设置', 0, 50, 1, '[]', '', 'iconfont-tig icon-shezhi', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000464, 'deliverManage', '发货管理', 10000444, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000468, 'salesman', '分销', 0, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000469, 'overviewManage', '分销概览', 10000468, 50, 1, '[]', '', 'iconfont-tig icon-yingxiaogailan', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000470, 'salesmanProduct', '分销商品', 10000468, 50, 1, '[]', '', 'iconfont-tig icon-fenxiaoshangpin', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000471, 'salesmanProductManage', '商品佣金管理', 10000470, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000472, 'AnalysisTableManage', '成交分析', 10000470, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000473, 'performanceSettlement', '分销结算', 10000468, 50, 1, '[]', '', 'iconfont-tig icon-fenxiaojiesuan', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000474, 'performanceSettlementManage', '业绩结算', 10000473, 50, 1, '[]', '', '', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000475, 'noticeManage', '内容管理', 10000468, 50, 1, '[]', '', 'iconfont-tig icon-wenzhangguanli', 0, 'shop');
INSERT INTO authority (authority_id, authority_sn, authority_name, parent_id, sort_order, is_show, child_auth, route_link, authority_ico, is_system, admin_type) VALUES (10000476, 'materialManage', '素材管理', 10000475, 50, 1, '[]', '', '', 0, 'shop');

# 删除的权限菜单
DELETE FROM authority WHERE authority_sn = 'productActivityManage' AND admin_type = 'admin';
DELETE FROM authority WHERE authority_sn = 'appVersionManage' AND admin_type = 'admin';
DELETE FROM authority WHERE authority_sn = 'paymentManage' AND admin_type = 'admin';
DELETE FROM authority WHERE authority_sn = 'cesh' AND admin_type = 'admin';
DELETE FROM authority WHERE authority_sn = 'product' AND admin_type = 'shop';
DELETE FROM authority WHERE authority_sn = 'order' AND admin_type = 'shop';
DELETE FROM authority WHERE authority_sn = 'shopShippingTypeManage' AND admin_type = 'shop';
DELETE FROM authority WHERE authority_sn = 'testManage' AND admin_type = 'admin';
DELETE FROM authority WHERE authority_sn = 'merchantMultilingualManage' AND admin_type = 'shop';
DELETE FROM authority WHERE authority_sn = 'shopTranslationContentManage' AND admin_type = 'shop';
DELETE FROM authority WHERE authority_sn = 'liveManage' AND admin_type = 'admin';

# 更新的权限菜单
UPDATE authority SET authority_sn = 'panel', authority_name = '面板', parent_id = 0, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/index/', authority_ico = 'iconfont-tig icon-jingying', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'panel' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'product', authority_name = '商品', parent_id = 0, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'product/list/', authority_ico = 'iconfont-tig icon-shangpin1', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'product' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productManage', authority_name = '商品列表', parent_id = 10000410, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productModifyManage"}]', route_link = 'product/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'categoryManage', authority_name = '商品类目', parent_id = 10000410, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productCategoryModifyManage"}]', route_link = 'product/category/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'categoryManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'promotion', authority_name = '营销', parent_id = 0, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'promotion/manage/list/', authority_ico = 'iconfont-tig icon-maiyizengyi', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'promotion' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'consoleManage', authority_name = '概览', parent_id = 1, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/index/', authority_ico = 'iconfont-tig icon-yingxiaogailan', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'consoleManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'order', authority_name = '订单', parent_id = 0, sort_order = 54, is_show = 1, child_auth = '[]', route_link = 'order/list/', authority_ico = 'iconfont-tig icon-dingdan1', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'order' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'decorate', authority_name = '装修', parent_id = 0, sort_order = 55, is_show = 1, child_auth = '[]', route_link = 'decorate/theme_style/info/', authority_ico = 'iconfont-tig icon-zhuangxiu', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'decorate' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'content', authority_name = '内容', parent_id = 0, sort_order = 57, is_show = 1, child_auth = '[]', route_link = 'content', authority_ico = 'iconfont-tig icon-gongsiqiye', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'content' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'user', authority_name = '会员', parent_id = 0, sort_order = 58, is_show = 1, child_auth = '[]', route_link = 'user', authority_ico = 'iconfont-tig icon-huiyuan3', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'user' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'finance', authority_name = '财务', parent_id = 0, sort_order = 57, is_show = 1, child_auth = '[]', route_link = 'finance', authority_ico = 'iconfont-tig icon-shuju', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'finance' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'authority', authority_name = '权限', parent_id = 0, sort_order = 60, is_show = 1, child_auth = '[]', route_link = 'authority', authority_ico = 'iconfont-tig icon-quanxian1', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'authority' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'setting', authority_name = '设置', parent_id = 0, sort_order = 61, is_show = 1, child_auth = '[]', route_link = 'setting/config/base/', authority_ico = 'iconfont-tig icon-shezhi', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'setting' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'authorityManage', authority_name = '权限目录', parent_id = 10000430, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"authorityUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"authorityDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"authorityBatchManage"}]', route_link = 'authority/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'authorityManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'brandManage', authority_name = '商品品牌', parent_id = 10000410, sort_order = 52, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"brandModifyManage"}]', route_link = 'product/brand/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'brandManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productBatch', authority_name = '批量操作', parent_id = 2, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'product/product_batch/', authority_ico = 'iconfont-tig icon-piliangcaozuo', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productBatch' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'commentManage', authority_name = '商品评价', parent_id = 10000410, sort_order = 53, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"commentModifyManage"}]', route_link = 'product/comment/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'commentManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mobileDecorate', authority_name = '移动端装修', parent_id = 9, sort_order = 50, is_show = 1, child_auth = '[]', route_link = '-', authority_ico = 'iconfont-tig icon-yidongduanzhuangxiu', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mobileDecorate' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mobileDecorateManage', authority_name = '页面管理', parent_id = 27, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"mobileDecorateModifyManage"}]', route_link = 'decorate/mobile_decorate/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mobileDecorateManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productAttributesTplManage', authority_name = '属性模板', parent_id = 10000410, sort_order = 53, is_show = 1, child_auth = '[{"auth_name":"\\u5546\\u54c1\\u5c5e\\u6027\\u6a21\\u677f\\u7f16\\u8f91","auth_sn":"productAttributesTplModifyManage"},{"auth_name":"\\u5546\\u54c1\\u5c5e\\u6027\\u7f16\\u8f91","auth_sn":"productAttributesGroupModifyManage"}]', route_link = 'product/product_attributes_tpl/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productAttributesTplManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productServicesManage', authority_name = '商品服务', parent_id = 10000410, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productServicesModifyManage"}]', route_link = 'product/product_services/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productServicesManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'orderManage', authority_name = '全部订单', parent_id = 10000414, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u53d1\\u8d27","auth_sn":"orderDeliverManage"},{"auth_name":"\\u6536\\u8d27","auth_sn":"orderConfirmReceiptManage"},{"auth_name":"\\u4fee\\u6539\\u6536\\u8d27\\u4eba","auth_sn":"orderModifyConsigneeManage"},{"auth_name":"\\u4fee\\u6539\\u914d\\u9001\\u4fe1\\u606f","auth_sn":"orderModifyShippingManage"},{"auth_name":"\\u4fee\\u6539\\u8ba2\\u5355\\u91d1\\u989d","auth_sn":"orderModifyMoneyManage"},{"auth_name":"\\u53d6\\u6d88\\u8ba2\\u5355","auth_sn":"cancelOrderManage"},{"auth_name":"\\u8ba2\\u5355\\u786e\\u8ba4","auth_sn":"setConfirmManage"},{"auth_name":"\\u8f6f\\u5220\\u9664","auth_sn":"delOrderManage"},{"auth_name":"\\u62c6\\u5355","auth_sn":"splitStoreOrderManage"},{"auth_name":"\\u8bbe\\u4e3a\\u5df2\\u652f\\u4ed8","auth_sn":"setPaidManage"},{"auth_name":"\\u4fee\\u6539\\u5546\\u54c1\\u4fe1\\u606f","auth_sn":"modifyProductManage"},{"auth_name":"\\u8bbe\\u7f6e\\u5546\\u5bb6\\u5907\\u6ce8","auth_sn":"setAdminNoteManage"},{"auth_name":"\\u6dfb\\u52a0\\u8ba2\\u5355\\u65e5\\u5fd7","auth_sn":"orderLogModifyManage"}]', route_link = 'order/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'orderManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productAutoManage', authority_name = '商品自动上下架', parent_id = 2, sort_order = 56, is_show = 0, child_auth = '[]', route_link = 'product/product_auto/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productAutoManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productInventoryLogManage', authority_name = '库存日志', parent_id = 10000411, sort_order = 57, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productInventoryLogModifyManage"}]', route_link = 'product/product_inventory_log/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productInventoryLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productBatchImageManage', authority_name = '图片批量处理', parent_id = 19, sort_order = 55, is_show = 0, child_auth = '[]', route_link = 'product/product_batch/image/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productBatchImageManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productBatchExportManage', authority_name = '批量导出', parent_id = 19, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productBatchExportUpdateManage"}]', route_link = 'product/product_batch/export/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productBatchExportManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productBatchAddManage', authority_name = '批量上传', parent_id = 19, sort_order = 52, is_show = 1, child_auth = '[{"auth_name":"\\u6279\\u91cf\\u4e0a\\u4f20","auth_sn":"productBatchModifyManage"}]', route_link = 'product/product_batch/add/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productBatchAddManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productBatchEditManage', authority_name = '批量修改', parent_id = 19, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u6279\\u91cf\\u4fee\\u6539","auth_sn":"productBatchEditManage"}]', route_link = 'product/product_batch/edit/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productBatchEditManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'config', authority_name = '系统设置', parent_id = 15, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'setting/cofnig/', authority_ico = 'iconfont-tig icon-xitongshezhi', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'config' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'configManage', authority_name = '商城设置', parent_id = 15, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u4fdd\\u5b58\\u5546\\u57ce\\u57fa\\u7840\\u8bbe\\u7f6e","auth_sn":"saveBasicManage"},{"auth_name":"\\u57fa\\u7840\\u8bbe\\u7f6e\\u66f4\\u65b0","auth_sn":"settingSaveManage"},{"auth_name":"\\u8bbe\\u7f6e\\u7f16\\u8f91","auth_sn":"settingUpdateManage"},{"auth_name":"\\u53d1\\u9001\\u6d4b\\u8bd5\\u90ae\\u4ef6","auth_sn":"sendTestEmailModifyManage"},{"auth_name":"\\u751f\\u6210\\u5e73\\u53f0\\u8bc1\\u4e66","auth_sn":"platformCertificateModifyManage"},{"auth_name":"\\u76f8\\u518c\\u4fee\\u6539","auth_sn":"galleryModifyManage"},{"auth_name":"\\u76f8\\u518c\\u56fe\\u7247\\u4fee\\u6539","auth_sn":"galleryPicModifyManage"},{"auth_name":"\\u76f8\\u518c\\u7ba1\\u7406","auth_sn":"galleryManage"},{"auth_name":"\\u76f8\\u518c\\u56fe\\u7247\\u7ba1\\u7406","auth_sn":"galleryPicManage"},{"auth_name":"\\u89c6\\u9891\\u7ba1\\u7406","auth_sn":"galleryVideoManage"}]', route_link = 'setting/config/base/', authority_ico = 'iconfont-tig icon-shangchengshezhi', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'configManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'adminUserManage', authority_name = '管理员列表', parent_id = 10000428, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"adminUserUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"adminUserDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"adminUserBatchManage"},{"auth_name":"\\u8d26\\u6237\\u4fee\\u6539","auth_sn":"modifyManageAccountsManage"},{"auth_name":"\\u6d88\\u606f\\u8bbe\\u7f6e","auth_sn":"adminMsgModifyManage"}]', route_link = 'authority/admin_user/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'adminUserManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'couponManage', authority_name = '优惠券', parent_id = 10000413, sort_order = 1, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"promotionCouponModifyManage"}]', route_link = 'promotion/coupon/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'couponManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'articleManage', authority_name = '文章列表', parent_id = 10000421, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"articleModifyManage"}]', route_link = 'content/article/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'articleManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'articleCategoryManage', authority_name = '文章分类', parent_id = 10000421, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"articleCategoryModifyManage"}]', route_link = 'content/article_category/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'articleCategoryManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'exchangeOrderManage', authority_name = '积分订单', parent_id = 10000414, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'order/exchange_order/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'exchangeOrderManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'messageLogManage', authority_name = '站内信', parent_id = 10000424, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"userMessageLogModifyManage"}]', route_link = 'user/message_log/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'messageLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userManage', authority_name = '会员列表', parent_id = 10000422, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u6dfb\\u52a0","auth_sn":"userCreateManage"},{"auth_name":"\\u7f16\\u8f91","auth_sn":"userModifyManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"userDelManage"},{"auth_name":"\\u66f4\\u65b0\\u5b57\\u6bb5","auth_sn":"userModifyFieldManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"userBatchManage"},{"auth_name":"\\u8d44\\u91d1\\u7ba1\\u7406","auth_sn":"fundManagementManage"}]', route_link = 'user/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'aftersalesManage', authority_name = '售后申请', parent_id = 10000415, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"aftersalesModifyManage"}]', route_link = 'order/aftersales/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'aftersalesManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'orderExportManage', authority_name = '订单导出', parent_id = 10000414, sort_order = 55, is_show = 1, child_auth = '[]', route_link = 'order/order_export/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'orderExportManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mailManage', authority_name = '邮箱服务器', parent_id = 38, sort_order = 53, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"settingSaveMailManage"}]', route_link = 'setting/config/mail/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mailManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mailTemplateManage', authority_name = '邮件模板', parent_id = 38, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"mailTemplatesUpdateManage"}]', route_link = 'setting/config/mail_template/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mailTemplateManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'messageTypeManage', authority_name = '消息管理', parent_id = 10000405, sort_order = 53, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"messageTypeUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"messageTypeDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"messageTypeBatchManage"},{"auth_name":"\\u751f\\u6210\\u5c0f\\u7a0b\\u5e8f\\u6d88\\u606f\\u6a21\\u677f","auth_sn":"miniProgramMessageTemplateManage"},{"auth_name":"\\u540c\\u6b65\\u5c0f\\u7a0b\\u5e8f\\u6d88\\u606f\\u6a21\\u677f","auth_sn":"miniProgramMessageTemplateSyncManage"},{"auth_name":"\\u751f\\u6210\\u516c\\u4f17\\u53f7\\u6d88\\u606f\\u6a21\\u677f","auth_sn":"wechatMessageTemplateManage"},{"auth_name":"\\u540c\\u6b65\\u516c\\u4f17\\u53f7\\u6d88\\u606f\\u6a21\\u677f","auth_sn":"wechatMessageTemplateSyncManage"},{"auth_name":"\\u65e5\\u5fd7\\u7ba1\\u7406","auth_sn":"accessLogModifyManage"}]', route_link = 'setting/config/message_type/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'messageTypeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shipping', authority_name = '配送设置组', parent_id = 15, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'setting/shipping/', authority_ico = 'iconfont-tig icon-peisongshezhi', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shipping' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'logisticsCompanyManage', authority_name = '物流公司', parent_id = 55, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"logisticsCompanyUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"logisticsCompanyDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"logisticsCompanyBatchManage"}]', route_link = 'setting/shipping/logistics_company/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'logisticsCompanyManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shippingTypeManage', authority_name = '配送类型', parent_id = 55, sort_order = 51, is_show = 0, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"shippingTypeUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"shippingTypeDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"shippingTypeBatchManage"}]', route_link = 'setting/shipping/shipping_type/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shippingTypeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shippingTplManage', authority_name = '运费模板', parent_id = 55, sort_order = 52, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"shippingTplUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"shippingTplDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"shippingTplBatchManage"}]', route_link = 'setting/shipping/shipping_tpl/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shippingTplManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'seckillManage', authority_name = '限时秒杀', parent_id = 10000413, sort_order = 2, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"seckillModifyManage"}]', route_link = 'promotion/seckill/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'seckillManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'regionManage', authority_name = '地区管理', parent_id = 38, sort_order = 55, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"regionUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"regionDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"regionBatchManage"}]', route_link = 'setting/region/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'regionManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'pcDecorate', authority_name = 'PC端装修', parent_id = 9, sort_order = 50, is_show = 1, child_auth = '[]', route_link = '-', authority_ico = 'iconfont-tig icon-PCduanzhuangxiu', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'pcDecorate' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'pcDecorateManage', authority_name = '首页装修', parent_id = 62, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u53d1\\u5e03","auth_sn":"decoratePublishManage"},{"auth_name":"\\u8bbe\\u4e3a\\u9996\\u9875","auth_sn":"decorateSetHomeManage"},{"auth_name":"\\u7f16\\u8f91","auth_sn":"decorateModifyManage"},{"auth_name":"\\u6a21\\u5757\\u7f16\\u8f91","auth_sn":"decorateDiscreteModifyManage"},{"auth_name":"\\u5b58\\u5165\\u8349\\u7a3f","auth_sn":"decorateSaveDraftManage"}]', route_link = 'decorate/pc_decorate/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'pcDecorateManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'friendLinksManage', authority_name = '友情链接', parent_id = 38, sort_order = 56, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"friendLinksUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"friendLinksDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"friendLinksBatchManage"}]', route_link = 'setting/friend_links/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'friendLinksManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'pointsExchangeManage', authority_name = '积分商品', parent_id = 10000413, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"promotionPointsExchangeModifyManage"}]', route_link = 'promotion/points_exchange/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'pointsExchangeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'signInSettingManage', authority_name = '积分签到', parent_id = 10000413, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"signInSettingModifyManage"}]', route_link = 'promotion/sign_in_setting/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'signInSettingManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'rechargeSettingManage', authority_name = '余额充值', parent_id = 10000413, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"rechargeSettingModifyManage"}]', route_link = 'promotion/recharge_setting/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'rechargeSettingManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'adminRoleManage', authority_name = '角色列表', parent_id = 10000428, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"adminRoleUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"adminRoleDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"adminRoleBatchManage"}]', route_link = 'authority/admin_role/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'adminRoleManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'adminLogManage', authority_name = '操作日志', parent_id = 10000428, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'authority/admin_log/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'adminLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'suppliersManage', authority_name = '供应商列表', parent_id = 10000429, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u5220\\u9664","auth_sn":"suppliersDelManage"},{"auth_name":"\\u7f16\\u8f91","auth_sn":"suppliersUpdateManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"suppliersBatchManage"}]', route_link = 'authority/suppliers/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'suppliersManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'feedbackManage', authority_name = '会员留言', parent_id = 10000422, sort_order = 53, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"feedbackModifyManage"}]', route_link = 'user/feedback/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'feedbackManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'pcDecorateOtherManage', authority_name = '其它页面', parent_id = 62, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"pcDecorateOtherUpdateManage"}]', route_link = 'decorate/pc_decorate/other/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'pcDecorateOtherManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userTypeManage', authority_name = '会员类型', parent_id = 77, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'user/user_type/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userTypeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userRightManage', authority_name = '会员权益', parent_id = 77, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'user/user_right/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userRightManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'agreementManage', authority_name = '会员协议', parent_id = 77, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'user/agreement/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'agreementManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'integralLogManage', authority_name = '积分日志', parent_id = 10000440, sort_order = 56, is_show = 1, child_auth = '[]', route_link = 'user/integral_log/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'integralLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'pcNavigationManage', authority_name = '导航栏', parent_id = 62, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"pcNavigationModifyManage"}]', route_link = 'decorate/pc_navigation/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'pcNavigationManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'pcCatFloorManage', authority_name = '分类抽屉', parent_id = 62, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"pcCatFloorModifyManage"}]', route_link = 'decorate/pc_cat_floor/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'pcCatFloorManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'accountPanelManage', authority_name = '资金总览', parent_id = 10000440, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'finance/account_panel/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'accountPanelManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userBalanceLogManage', authority_name = '余额日志', parent_id = 10000442, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'finance/user_balance_log/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userBalanceLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userRechargeOrderManage', authority_name = '充值管理', parent_id = 10000440, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'finance/user_recharge_order/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userRechargeOrderManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userWithdrawApplyManage', authority_name = '提现管理', parent_id = 10000440, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'finance/user_withdraw_apply/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userWithdrawApplyManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'payLogManage', authority_name = '交易日志', parent_id = 10000442, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'finance/paylog/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'payLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'refundApplyManage', authority_name = '退款申请', parent_id = 10000441, sort_order = 55, is_show = 1, child_auth = '[]', route_link = 'finance/refund_apply/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'refundApplyManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userInvoice', authority_name = '发票管理', parent_id = 12, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'finance/user_invoice/', authority_ico = 'iconfont-tig icon-fapiaoguanli', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userInvoice' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userInvoiceManage', authority_name = '资质审核', parent_id = 90, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"userInvoiceUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"userInvoiceDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"userInvoiceBatchManage"}]', route_link = 'finance/user_invoice/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userInvoiceManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'orderInvoiceManage', authority_name = '发票申请', parent_id = 90, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"orderInvoiceUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"orderInvoiceDelManage"},{"auth_name":"\\u6279\\u91cf\\u64cd\\u4f5c","auth_sn":"orderInvoiceBatchManage"}]', route_link = 'finance/order_invoice/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'orderInvoiceManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'statisticsOrder', authority_name = '销售概览', parent_id = 10000408, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_order/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'statisticsOrder' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'themeStyleManage', authority_name = '主题风格', parent_id = 9, sort_order = 49, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"themeCategoryDecorateManage"}]', route_link = 'decorate/theme_style/info/', authority_ico = 'iconfont-tig icon-zhutifengge', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'themeStyleManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'statisticsSale', authority_name = '销售明细', parent_id = 10000408, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_sale/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'statisticsSale' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'saleTargets', authority_name = '销售指标', parent_id = 10000408, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/sale_targets/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'saleTargets' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'statisticsGoods', authority_name = '销售排行', parent_id = 10000408, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_goods/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'statisticsGoods' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'statisticsUser', authority_name = '用户概览', parent_id = 10000409, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_user/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'statisticsUser' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'statisticsAccess', authority_name = '访问统计', parent_id = 10000409, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_access/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'statisticsAccess' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'consumerRanking', authority_name = '消费排行', parent_id = 10000409, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/consumer_ranking/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'consumerRanking' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'newMembers', authority_name = '新增会员', parent_id = 10000409, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/new_members/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'newMembers' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mobileCatNavManage', authority_name = '分类导航', parent_id = 27, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"mobileCatNavModifyManage"}]', route_link = 'decorate/mobile_cat_nav/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mobileCatNavManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'ziyin', authority_name = '自营店铺1', parent_id = 261, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'ziying/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'ziyin' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'xieyi', authority_name = '协议', parent_id = 0, sort_order = 63, is_show = 0, child_auth = '[]', route_link = 'xieyi/', authority_ico = 'lyecs-defined-iconfont lyecs-defined-icon-dianshi', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'xieyi' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'xiey', authority_name = '协议1', parent_id = 263, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'xiey/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'xiey' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'AfterSalesServiceManage', authority_name = '售后服务设置', parent_id = 38, sort_order = 55, is_show = 0, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"settingSaveAfterSalesManage"}]', route_link = 'setting/config/after_sales_service/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'AfterSalesServiceManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mobileNavManage', authority_name = '主导航栏', parent_id = 27, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91\\u5bfc\\u822a\\u680f","auth_sn":"mobileNavUpdateManage"}]', route_link = 'decorate/mobile_decorate/nav', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mobileNavManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'adminMerchant', authority_name = '商户', parent_id = 0, sort_order = 54, is_show = 1, child_auth = '[]', route_link = 'adminMerchant/apply/list/', authority_ico = 'iconfont-tig icon-31quanbushangpin', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'adminMerchant' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'applyManage', authority_name = '入驻申请', parent_id = 276, sort_order = 49, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"merchantApplyModifyManage"}]', route_link = 'adminMerchant/apply/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'applyManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'adminMerchantManage', authority_name = '商户管理', parent_id = 276, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"merchantModifyManage"},{"auth_name":"\\u8d26\\u6237\\u7f16\\u8f91","auth_sn":"accountModifyManage"}]', route_link = 'adminMerchant/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'adminMerchantManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'adminMerchantSettingsManage', authority_name = '商户设置', parent_id = 276, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"adminMerchantSettingsUpdateManage"}]', route_link = 'adminMerchant/merchantSettings/info', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'adminMerchantSettingsManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopManage', authority_name = '店铺列表', parent_id = 281, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'shop/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'shopManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'accountManage', authority_name = '店铺资金列表', parent_id = 281, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'shop/account/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'accountManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'refundLogManage', authority_name = '退款日志', parent_id = 10000441, sort_order = 56, is_show = 1, child_auth = '[]', route_link = 'finance/refund_log/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'refundLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'panel', authority_name = '店铺', parent_id = 0, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/index/', authority_ico = 'iconfont-tig icon-jingying', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'panel' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'promotion', authority_name = '营销', parent_id = 0, sort_order = 56, is_show = 1, child_auth = '[]', route_link = 'promotion/coupon/list/', authority_ico = 'iconfont-tig icon-maiyizengyi', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'promotion' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'productManage', authority_name = '商品列表', parent_id = 10000450, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productModifyManage"}]', route_link = 'product/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'productManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'productGroupManage', authority_name = '商品分组', parent_id = 10000410, sort_order = 52, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productGroupModifyManage"}]', route_link = 'product/product_group/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productGroupManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopAccountRaplyManage', authority_name = '提现申请', parent_id = 281, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'shop/shopAccountRaply/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'shopAccountRaplyManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'capitalfund', authority_name = '财务中心', parent_id = 10001, sort_order = 7, is_show = 1, child_auth = '[]', route_link = 'capitalfund/dashboard/index/', authority_ico = 'iconfont-tig icon-31tianmaobao', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'capitalfund' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'dashboardManage', authority_name = '资金概览', parent_id = 10000291, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'capitalfund/dashboard/index/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'dashboardManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'balanceManage', authority_name = '店铺资金', parent_id = 10000291, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'capitalfund/balance/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'balanceManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'withdrawManage', authority_name = '提现管理', parent_id = 10000291, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'capitalfund/withdraw/index/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'withdrawManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'mobileShopDecorate', authority_name = '页面管理', parent_id = 10000311, sort_order = 1, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/mobile_shop_decorate', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'mobileShopDecorate' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'consoleManage', authority_name = '概览', parent_id = 10001, sort_order = 1, is_show = 1, child_auth = '[]', route_link = 'panel/index/', authority_ico = 'iconfont-tig icon-yingxiaogailan', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'consoleManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'statisticsOrder', authority_name = '销售概览', parent_id = 10000443, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_order/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'statisticsOrder' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'statisticsSale', authority_name = '销售明细', parent_id = 10000443, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_sale/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'statisticsSale' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'statisticsGoods', authority_name = '销售排行', parent_id = 10000443, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'panel/statistics_goods/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'statisticsGoods' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'shopProductCategoryManage', authority_name = '商品分类', parent_id = 10000450, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'product/shop_product_category/list', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'shopProductCategoryManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'orderManage', authority_name = '全部订单', parent_id = 10000444, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u53d1\\u8d27","auth_sn":"orderDeliverManage"},{"auth_name":"\\u6536\\u8d27","auth_sn":"orderConfirmReceiptManage"},{"auth_name":"\\u4fee\\u6539\\u6536\\u8d27\\u4eba","auth_sn":"orderModifyConsigneeManage"},{"auth_name":"\\u4fee\\u6539\\u914d\\u9001\\u4fe1\\u606f","auth_sn":"orderModifyShippingManage"},{"auth_name":"\\u4fee\\u6539\\u8ba2\\u5355\\u91d1\\u989d","auth_sn":"orderModifyMoneyManage"},{"auth_name":"\\u53d6\\u6d88\\u8ba2\\u5355","auth_sn":"cancelOrderManage"},{"auth_name":"\\u8ba2\\u5355\\u786e\\u8ba4","auth_sn":"setConfirmManage"},{"auth_name":"\\u8f6f\\u5220\\u9664","auth_sn":"delOrderManage"},{"auth_name":"\\u62c6\\u5355","auth_sn":"splitStoreOrderManage"},{"auth_name":"\\u8bbe\\u4e3a\\u5df2\\u652f\\u4ed8","auth_sn":"setPaidManage"},{"auth_name":"\\u4fee\\u6539\\u5546\\u54c1\\u4fe1\\u606f","auth_sn":"modifyProductManage"},{"auth_name":"\\u8bbe\\u7f6e\\u5546\\u5bb6\\u5907\\u6ce8","auth_sn":"setAdminNoteManage"},{"auth_name":"\\u6dfb\\u52a0\\u8ba2\\u5355\\u65e5\\u5fd7","auth_sn":"orderLogModifyManage"}]', route_link = 'order/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'orderManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'aftersalesManage', authority_name = '售后订单', parent_id = 10000445, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"aftersalesModifyManage"}]', route_link = 'order/aftersales/list', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'aftersalesManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'orderExportManage', authority_name = '订单导出', parent_id = 10000444, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'order/order_export/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'orderExportManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'productGroupManage', authority_name = '商品分组', parent_id = 10000450, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productGroupModifyManage"}]', route_link = 'product/product_group/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'productGroupManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'shop', authority_name = '店铺', parent_id = 0, sort_order = 54, is_show = 1, child_auth = '[]', route_link = 'shop/list/', authority_ico = 'iconfont-tig icon-guanli', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shop' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopManage', authority_name = '店铺列表', parent_id = 10000416, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'shop/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shopManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopAccountManage', authority_name = '资金概览', parent_id = 10000417, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'shop/shopAccount/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shopAccountManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopAccountRaplyManage', authority_name = '提现管理', parent_id = 10000417, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'shop/shopAccountRaply/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shopAccountRaplyManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'merchantSetting', authority_name = '店铺设置', parent_id = 10000463, sort_order = 1, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/mobile_shop_decorate', authority_ico = 'iconfont-tig icon-31shezhi', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'merchantSetting' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'couponManage', authority_name = '优惠券', parent_id = 10000457, sort_order = 1, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"promotionCouponModifyManage"}]', route_link = 'promotion/coupon/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'couponManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'seckillManage', authority_name = '限时秒杀', parent_id = 10000457, sort_order = 2, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"seckillModifyManage"}]', route_link = 'promotion/seckill/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'seckillManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'productActivityManage', authority_name = '优惠活动', parent_id = 10000457, sort_order = 3, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"productPromotionModifyManage"}]', route_link = 'promotion/product_activity/list', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'productActivityManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'ShopTeamManage', authority_name = '店铺设置', parent_id = 10000311, sort_order = 2, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/shop_team/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'ShopTeamManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'EmployeeManagement', authority_name = '员工管理', parent_id = 10000458, sort_order = 4, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/employee/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'EmployeeManagement' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'ShopInfoManage', authority_name = '店铺信息', parent_id = 10000311, sort_order = 3, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/shop_info', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'ShopInfoManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'ShopRoleManage', authority_name = '角色管理', parent_id = 10000458, sort_order = 5, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/shop_role/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'ShopRoleManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'shopShipping', authority_name = '配送设置', parent_id = 10000463, sort_order = 2, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/shop_shipping/', authority_ico = 'iconfont-tig icon-peisongshezhi', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'shopShipping' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'shopShippingTplManage', authority_name = '运费模板', parent_id = 10000322, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/shop_shipping/shop_shipping_tpl/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'shopShippingTplManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'fullReductionManage', authority_name = '满减活动', parent_id = 10000413, sort_order = 3, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"fullReductionUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"fullReductionDelManage"}]', route_link = 'promotion/full_reduction/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'fullReductionManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'rewardGiftManage', authority_name = '满赠活动', parent_id = 10000413, sort_order = 4, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"rewardGiftUpdateManage"},{"auth_name":"\\u5220\\u9664","auth_sn":"rewardGiftDelManage"}]', route_link = 'promotion/reward_gift/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'rewardGiftManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'productGiftManage', authority_name = '活动赠品', parent_id = 10000457, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'promotion/product_gift/list', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'productGiftManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'productGiftManage', authority_name = '活动赠品', parent_id = 10000413, sort_order = 10, is_show = 1, child_auth = '[]', route_link = 'promotion/product_gift/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'productGiftManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'limitdiscountManage', authority_name = '限时折扣', parent_id = 10000413, sort_order = 5, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"timeDiscountModifyManage"}]', route_link = 'promotion/limitdiscount_gift/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'limitdiscountManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'promotionManage', authority_name = '营销概览', parent_id = 5, sort_order = 0, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"promotionUpdateManage"}]', route_link = 'promotion/manage/list/', authority_ico = 'iconfont-tig icon-yingxiaogailan', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'promotionManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'investmentManage', authority_name = '招商内容', parent_id = 276, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'adminMerchant/investment/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'investmentManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopSettingsManage', authority_name = '店铺设置', parent_id = 10000416, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"shopSettingsUpdateManage"}]', route_link = 'shop/shopSettings/info', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shopSettingsManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'shopFundsManage', authority_name = '店铺资金', parent_id = 10000417, sort_order = 51, is_show = 1, child_auth = '[]', route_link = 'shop/shopFunds/list', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'shopFundsManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'financialLogManage', authority_name = '资金日志', parent_id = 10000417, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'shop/financialLog/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'financialLogManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'EmployeeLogManagement', authority_name = '操作日志', parent_id = 10000458, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'merchant_setting/employeeLog/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'EmployeeLogManagement' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'warehouseManage', authority_name = '仓库管理', parent_id = 10000347, sort_order = 55, is_show = 1, child_auth = '[]', route_link = 'cross/warehouse/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'warehouseManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'salesman', authority_name = '分销', parent_id = 0, sort_order = 56, is_show = 1, child_auth = '[]', route_link = 'salesman/index/', authority_ico = 'iconfont-tig icon-fenxiao', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'salesman' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'overviewManage', authority_name = '分销概览', parent_id = 10000337, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'salesman/index/', authority_ico = 'iconfont-tig icon-yingxiaogailan', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'overviewManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'promoterManage', authority_name = '分销员管理', parent_id = 10000360, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"salesmanModifyManage"}]', route_link = 'salesman/promoter/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'promoterManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'promoteModeManage', authority_name = '分销模式', parent_id = 10000418, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91\\u914d\\u7f6e","auth_sn":"salesmanConfigModifyManage"}]', route_link = 'salesman/promoteMode/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'promoteModeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'salesmanProduct', authority_name = '分销商品', parent_id = 10000337, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'salesman/product/list/', authority_ico = 'iconfont-tig icon-fenxiaoshangpin', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'salesmanProduct' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'performanceSettlementManage', authority_name = '业绩结算', parent_id = 10000361, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u4eba\\u5de5\\u7ed3\\u7b97","auth_sn":"salesmanSettlementManage"}]', route_link = 'salesman/performanceSettlement/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'performanceSettlementManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'salesmanDetailedManage', authority_name = '分销员明细', parent_id = 10000360, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'salesman/salesmanDetailed/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'salesmanDetailedManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'performanceSettlementSettingManage', authority_name = '结算方案设置', parent_id = 10000361, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'salesman/performanceSettlement/setting/index', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'performanceSettlementSettingManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'subgroupManage', authority_name = '分销员分组', parent_id = 10000360, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"salesmanGroupModifyManage"}]', route_link = 'salesman/subgroup/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'subgroupManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'noticeManage', authority_name = '内容管理', parent_id = 10000337, sort_order = 55, is_show = 1, child_auth = '[]', route_link = 'salesman/notice/list/', authority_ico = 'iconfont-tig icon-dingdanguanli', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'noticeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'materialCategoryManage', authority_name = '素材分类', parent_id = 10000346, sort_order = 2, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"salesmanCategoryModifyManage"}]', route_link = 'salesman/materialCategory/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'materialCategoryManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'materialManage', authority_name = '素材管理', parent_id = 10000346, sort_order = 3, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"salesmanMaterialModifyManage"}]', route_link = 'salesman/material/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'materialManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'RankingTableManage', authority_name = '分销员排行', parent_id = 10000360, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'salesman/overview/rankingTable/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'RankingTableManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'AnalysisTableManage', authority_name = '成交分析', parent_id = 10000341, sort_order = 3, is_show = 1, child_auth = '[]', route_link = 'salesman/overview/analysisTable/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'AnalysisTableManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'salesmanProductManage', authority_name = '商品佣金管理', parent_id = 10000341, sort_order = 1, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"salesmanProductModifyManage"}]', route_link = 'salesman/product/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'salesmanProductManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'salesmanManage', authority_name = '分销员', parent_id = 10000337, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'salesman/promoter/list/', authority_ico = 'iconfont-tig icon-fenxiaoyuan1', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'salesmanManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'performanceSettlement', authority_name = '分销结算', parent_id = 10000337, sort_order = 54, is_show = 1, child_auth = '[]', route_link = 'salesman/performanceSettlement/setting/index', authority_ico = 'iconfont-tig icon-fenxiaojiesuan', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'performanceSettlement' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'salesmanNoticeManage', authority_name = '分销攻略', parent_id = 10000346, sort_order = 1, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"salesmanContentModifyManage"}]', route_link = 'salesman/notice/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'salesmanNoticeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'licensed', authority_name = '授权信息', parent_id = 10000406, sort_order = 69, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"licensedModifyManage"}]', route_link = 'setting/licensed/index', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'licensed' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'multilingual', authority_name = '多语言管理', parent_id = 15, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'setting/multilingual/languagesList/list', authority_ico = 'iconfont-tig icon-duoyuyan1', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'multilingual' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'languagesListManage', authority_name = '语言管理', parent_id = 10000373, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"localesModifyManage"}]', route_link = 'setting/multilingual/languagesList/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'languagesListManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'verbalAssociationManage', authority_name = '语言关联设置', parent_id = 10000373, sort_order = 54, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"localesRelationModifyManage"}]', route_link = 'setting/multilingual/verbalAssociation/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'verbalAssociationManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'translationContentManage', authority_name = '翻译内容维护', parent_id = 10000373, sort_order = 51, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"translationsModifyManage"}]', route_link = 'setting/multilingual/translationContent/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'translationContentManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'currencyManagementManage', authority_name = '币种管理', parent_id = 10000373, sort_order = 52, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"currencyModifyManage"}]', route_link = 'setting/multilingual/currencyManagement/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'currencyManagementManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'classifyManage', authority_name = '分类页', parent_id = 27, sort_order = 52, is_show = 1, child_auth = '[]', route_link = 'decorate/mobile_decorate/classify/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'classifyManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'mobileUserManage', authority_name = '会员首页', parent_id = 27, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'decorate/mobile_decorate/user', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'mobileUserManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'logisticsManage', authority_name = '配送设置', parent_id = 55, sort_order = 50, is_show = 1, child_auth = '[{"auth_name":"\\u7f16\\u8f91","auth_sn":"settingSaveShippingManage"}]', route_link = 'setting/config/logistics/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'logisticsManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'areaCodeManage', authority_name = '区号管理', parent_id = 10000373, sort_order = 53, is_show = 1, child_auth = '[]', route_link = 'setting/multilingual/areaCode/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'areaCodeManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'eCardManage', authority_name = '电子卡券', parent_id = 10000413, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'promotion/e_card/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'eCardManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'eCardManage', authority_name = '电子卡券', parent_id = 10000457, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'promotion/e_card/list/', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'eCardManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'userCertificationManage', authority_name = '会员认证', parent_id = 10000423, sort_order = 2, is_show = 1, child_auth = '[]', route_link = 'user/user_certification/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userCertificationManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'userLevelProManage', authority_name = '会员等级设置', parent_id = 10000422, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'user/level_manage_pro/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'userLevelProManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'enquiryManage', authority_name = '商品询价', parent_id = 10000412, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'product/enquiry/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'enquiryManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'levelManageManage', authority_name = '会员等级设置', parent_id = 10000422, sort_order = 50, is_show = 1, child_auth = '[]', route_link = 'user/level_manage/list/', authority_ico = '', is_system = 0, admin_type = 'admin' WHERE authority_sn = 'levelManageManage' AND admin_type = 'admin';
UPDATE authority SET authority_sn = 'fullReductionManage', authority_name = '满减活动', parent_id = 10000457, sort_order = 50, is_show = 1, child_auth = '[]', route_link = '', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'fullReductionManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'rewardGiftManage', authority_name = '满赠活动', parent_id = 10000457, sort_order = 50, is_show = 1, child_auth = '[]', route_link = '', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'rewardGiftManage' AND admin_type = 'shop';
UPDATE authority SET authority_sn = 'limitdiscountManage', authority_name = '限时折扣', parent_id = 10000457, sort_order = 50, is_show = 1, child_auth = '[]', route_link = '', authority_ico = '', is_system = 0, admin_type = 'shop' WHERE authority_sn = 'limitdiscountManage' AND admin_type = 'shop';

